version: "3"
services:
  database:
    image: postgres:16.0-bookworm
    secrets:
      - postgresql_password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgresql_password
    volumes:
      - ${DATABASE_DIR:-./database_data}:/var/lib/postgresql/data
    deploy:
      replicas: 1

  redis:
    image: redis:7.2.1-bookworm
    volumes:
      - ${REDIS_DIR:-./redis_data}:/data
    deploy:
      replicas: 1

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    user: 0:0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ${BROKER_DIR:-./broker_data}/zookeeper/data:/var/lib/zookeeper/data
      - ${BROKER_DIR:-./broker_data}/zookeeper/log:/var/lib/zookeeper/log
    deploy:
      replicas: 1

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    user: 0:0
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ${BROKER_DIR:-./broker_data}/kafka/data:/var/lib/kafka/data
    deploy:
      replicas: 1

  users:
    image: ${SAPPHIRE_IMAGE:-sapphire}
    depends_on:
      - redis
      - database
      - kafka
    environment:
      DB_DSN: ${USERS_DB_DSN:-sqlite+aiosqlite:///users.db}
    secrets:
      - habr_oauth2_client_id
      - habr_oauth2_client_secret
    ports:
      - target: 8000
        published: ${USERS_PORT:-3000}
        mode: host
    command: ["users", "api", "serve"]
    deploy:
      replicas: 1

  projects:
    image: ${SAPPHIRE_IMAGE:-sapphire}
    environment:
      DB_DSN: ${PROJECTS_DB_DSN:-sqlite+aiosqlite:///projects.db}
    depends_on:
      - redis
      - database
      - kafka
    ports:
      - target: 8000
        published: ${PROJECTS_PORT:-3020}
        mode: host
    command: ["projects", "api", "serve"]
    deploy:
      replicas: 1

secrets:
  habr_oauth2_client_id:
    external: true
    name: ${HABR_OAUTH2_CLIENT_ID_NAME:-habr_oauth2_client_id}
  habr_oauth2_client_secret:
    external: true
    name: ${HABR_OAUTH2_CLIENT_SECRET_NAME:-habr_oauth2_client_secret}
  postgresql_password:
    external: true
    name: ${POSTGRESQL_PASSWORD_NAME:-postgresql_password}
