version: "3"
services:
  database:
    image: postgres:16.0-bookworm
    user: 0:0
    environment:
      POSTGRES_USER: sapphire
      POSTGRES_DB: sapphire
      POSTGRES_PASSWORD: P@ssw0rd
    volumes:
      - ./database_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:7.2.1-bookworm
    volumes:
      - ./redis_data:/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    user: 0:0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ./broker_data/zookeeper/data:/var/lib/zookeeper/data
      - ./broker_data/zookeeper/log:/var/lib/zookeeper/log
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    user: 0:0
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./broker_data/kafka/data:/var/lib/kafka/data
    ports:
      - 9091:9091
