version: "3"
services:
  database:
    image: postgres:16.0-bookworm
    secrets:
      - postgresql_password
    user: 0:0
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgresql_password
    volumes:
      - ${DATABASE_DIR:-./database_data}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
    deploy:
      replicas: 1

  redis:
    image: redis:7.2.1-bookworm
    volumes:
      - ${REDIS_DIR:-./redis_data}:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
    deploy:
      replicas: 1

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    user: 0:0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ${BROKER_DIR:-./broker_data}/zookeeper/data:/var/lib/zookeeper/data
      - ${BROKER_DIR:-./broker_data}/zookeeper/log:/var/lib/zookeeper/log
    healthcheck:
      test: nc -z localhost 2181 || exit -1
    deploy:
      replicas: 1

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    user: 0:0
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ${BROKER_DIR:-./broker_data}/kafka/data:/var/lib/kafka/data
    healthcheck:
      test: nc -z localhost 9091 || exit -1
    deploy:
      replicas: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9091
      SERVER_SERVLET_CONTEXT_PATH: ${KAFKA_UI_ROOT_PATH:-/kafka}
      AUTH_TYPE: LOGIN_FORM
      SPRING_SECURITY_USER_NAME: admin
      SPRING_SECURITY_USER_PASSWORD: ${KAFKA_UI_PASSWORD:-admin}
    healthcheck:
      test: wget --spider -q http://localhost:8080${KAFKA_UI_ROOT_PATH:-/kafka}/actuator/health
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.kafka.rule=PathPrefix(`${KAFKA_UI_ROOT_PATH:-/kafka}`)"
        - "traefik.http.routers.kafka.entrypoints=web" 
        - "traefik.http.routers.kafka.service=kafka"
        - "traefik.http.services.kafka.loadbalancer.server.port=8080"
      replicas: 1

  sapphire:
    image: ${SAPPHIRE_IMAGE:-sapphire}
    environment:
      MESSENGER__API__ROOT_URL: ${MESSENGER__API__ROOT_URL:-http://localhost:3000/messenger}
      MESSENGER__API__ROOT_PATH: ${MESSENGER__API__ROOT_PATH:-/messenger}
      MESSENGER__API__ALLOWED_ORIGINS: ${MESSENGER__API__ALLOWED_ORIGINS:-["http://localhost:3000"]}
      MESSENGER__BROKER__SERVERS: '["kafka:9091"]'
      MESSENGER__BROKER__TOPICS: '["chats"]'
      MESSENGER__DATABASE__DSN: ${MESSENGER__DATABASE__DSN:-postgresql+asyncpg://messenger:P%40ssw0rd@database:5432/messenger}
      NOTIFICATIONS__API__ROOT_URL: ${NOTIFICATIONS__API__ROOT_URL:-http://localhost:3000/notifications}
      NOTIFICATIONS__API__ROOT_PATH: ${NOTIFICATIONS__API__ROOT_PATH:-/notifications}
      NOTIFICATIONS__API__ALLOWED_ORIGINS: ${NOTIFICATIONS__API__ALLOWED_ORIGINS:-["http://localhost:3000"]}
      NOTIFICATIONS__BROKER__SERVERS: '["kafka:9091"]'
      NOTIFICATIONS__BROKER__TOPICS: '["notifications"]'
      NOTIFICATIONS__DATABASE__DSN: ${NOTIFICATIONS__DATABASE__DSN:-postgresql+asyncpg://notifications:P%40ssw0rd@database:5432/notifications}
      PROJECTS__API__ROOT_URL: ${PROJECTS__API__ROOT_URL:-http://localhost:3000/projects}
      PROJECTS__API__ROOT_PATH: ${PROJECTS__API__ROOT_PATH:-/projects}
      PROJECTS__API__ALLOWED_ORIGINS: ${PROJECTS__API__ALLOWED_ORIGINS:-["http://localhost:3000"]}
      PROJECTS__BROKER__SERVERS: '["kafka:9091"]'
      PROJECTS__DATABASE__DSN: ${PROJECTS__DATABASE__DSN:-postgresql+asyncpg://projects:P%40ssw0rd@database:5432/projects}
      STORAGE__API__ROOT_URL: ${STORAGE__API__ROOT_URL:-http://localhost:3000/storage}
      STORAGE__API__ROOT_PATH: ${STORAGE__API__ROOT_PATH:-/storage}
      STORAGE__API__ALLOWED_ORIGINS: ${STORAGE__API__ALLOWED_ORIGINS:-["http://localhost:3000"]}
      STORAGE__DATABASE__DSN: ${STORAGE__DATABASE__DSN:-postgresql+asyncpg://storage:P%40ssw0rd@database:5432/storage}
      USERS__API__ROOT_URL: ${USERS__API__ROOT_URL:-http://localhost:3000/users}
      USERS__API__ROOT_PATH: ${USERS__API__ROOT_PATH:-/users}
      USERS__API__ALLOWED_ORIGINS: ${USERS__API__ALLOWED_ORIGINS:-["http://localhost:3000"]}
      USERS__API__OAUTH2_HABR_CALLBACK_URL: ${USERS__API__OAUTH2_HABR_CALLBACK_URL:-http://localhost:3000/users/api/rest/auth/oauth2/habr/callback}
      USERS__CACHE__URL: "redis://redis:6379/0"
      USERS__DATABASE__DSN: ${USERS__DATABASE__DSN:-postgresql+asyncpg://users:P%40ssw0rd@database:5432/users}
    secrets:
      - target: users__jwt__access_token_public_key
        source: jwt_access_token_public_key
      - target: users__jwt__access_token_private_key
        source: jwt_access_token_private_key
      - target: users__jwt__refresh_token_public_key
        source: jwt_refresh_token_public_key
      - target: users__jwt__refresh_token_private_key
        source: jwt_refresh_token_private_key
      - target: storage__jwt__access_token_public_key
        source: jwt_access_token_public_key
      - target: storage__jwt__access_token_private_key
        source: jwt_access_token_private_key
      - target: storage__jwt__refresh_token_public_key
        source: jwt_refresh_token_public_key
      - target: storage__jwt__refresh_token_private_key
        source: jwt_refresh_token_private_key
      - target: projects__jwt__access_token_public_key
        source: jwt_access_token_public_key
      - target: projects__jwt__access_token_private_key
        source: jwt_access_token_private_key
      - target: projects__jwt__refresh_token_public_key
        source: jwt_refresh_token_public_key
      - target: projects__jwt__refresh_token_private_key
        source: jwt_refresh_token_private_key
      - target: notifications__jwt__access_token_public_key
        source: jwt_access_token_public_key
      - target: notifications__jwt__access_token_private_key
        source: jwt_access_token_private_key
      - target: notifications__jwt__refresh_token_public_key
        source: jwt_refresh_token_public_key
      - target: notifications__jwt__refresh_token_private_key
        source: jwt_refresh_token_private_key
      - target: messenger__jwt__access_token_public_key
        source: jwt_access_token_public_key
      - target: messenger__jwt__access_token_private_key
        source: jwt_access_token_private_key
      - target: messenger__jwt__refresh_token_public_key
        source: jwt_refresh_token_public_key
      - target: messenger__jwt__refresh_token_private_key
        source: jwt_refresh_token_private_key
    volumes:
      - ${USERS__API__MEDIA_DIR_PATH:-./media}:/media
    command: ["run"]
    healthcheck:
      test: >
        curl --fail http://localhost:8000/health &&
        curl --fail http://localhost:8010/health &&
        curl --fail http://localhost:8020/health &&
        curl --fail http://localhost:8030/health &&
        curl --fail http://localhost:8040/health
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.middlewares.messenger-stripprefix.stripprefix.prefixes=${MESSENGER__API__ROOT_PATH:-/messenger}"
        - "traefik.http.routers.messenger.middlewares=messenger-stripprefix"
        - "traefik.http.routers.messenger.rule=PathPrefix(`${MESSENGER__API__ROOT_PATH:-/messenger}`)"
        - "traefik.http.routers.messenger.service=messenger"
        - "traefik.http.routers.messenger.entrypoints=web" 
        - "traefik.http.services.messenger.loadbalancer.server.port=8000"
        - "traefik.http.middlewares.notifications-stripprefix.stripprefix.prefixes=${NOTIFICATIONS__API__ROOT_PATH:-/notifications}"
        - "traefik.http.routers.notifications.middlewares=notifications-stripprefix"
        - "traefik.http.routers.notifications.rule=PathPrefix(`${NOTIFICATIONS__API__ROOT_PATH:-/notifications}`)"
        - "traefik.http.routers.notifications.service=notifications"
        - "traefik.http.routers.notifications.entrypoints=web" 
        - "traefik.http.services.notifications.loadbalancer.server.port=8010"
        - "traefik.http.middlewares.projects-stripprefix.stripprefix.prefixes=${PROJECTS__API__ROOT_PATH:-/projects}"
        - "traefik.http.routers.projects.middlewares=projects-stripprefix"
        - "traefik.http.routers.projects.rule=PathPrefix(`${PROJECTS__API__ROOT_PATH:-/projects}`)"
        - "traefik.http.routers.projects.service=projects"
        - "traefik.http.routers.projects.entrypoints=web" 
        - "traefik.http.services.projects.loadbalancer.server.port=8020"
        - "traefik.http.middlewares.storage-stripprefix.stripprefix.prefixes=${STORAGE__API__ROOT_PATH:-/storage}"
        - "traefik.http.routers.storage.middlewares=storage-stripprefix"
        - "traefik.http.routers.storage.rule=PathPrefix(`${STORAGE__API__ROOT_PATH:-/storage}`)"
        - "traefik.http.routers.storage.service=storage"
        - "traefik.http.routers.storage.entrypoints=web"
        - "traefik.http.services.storage.loadbalancer.server.port=8030"
        - "traefik.http.middlewares.users-stripprefix.stripprefix.prefixes=${USERS__API__ROOT_PATH:-/users}"
        - "traefik.http.routers.users.middlewares=users-stripprefix"
        - "traefik.http.routers.users.rule=PathPrefix(`${USERS__API__ROOT_PATH:-/users}`)"
        - "traefik.http.routers.users.service=users"
        - "traefik.http.routers.users.entrypoints=web"
        - "traefik.http.services.users.loadbalancer.server.port=8040"
      update_config:
        order: start-first
      replicas: 1

  swagger:
    image: swaggerapi/swagger-ui
    environment:
      URLS: >
        [
          {
            "url": "${USERS__API__ROOT_URL:-http://localhost:3000/users}${USERS__API__ROOT_PATH}/openapi.json",
            "name": "Users",
          },
          {
            "url": "${STORAGE__API__ROOT_URL:-http://localhost:3000/storage}${STORAGE__API__ROOT_PATH}/openapi.json",
            "name": "Storage",
          },
          {
            "url": "${PROJECTS__API__ROOT_URL:-http://localhost:3000/projects}${PROJECTS__API__ROOT_PATH}/openapi.json",
            "name": "Projects",
          },
          {
            "url": "${NOTIFICATIONS__API__ROOT_URL:-http://localhost:3000/notifications}${NOTIFICATIONS__API__ROOT_PATH}/openapi.json",
            "name": "Notifications",
          },
          {
            "url": "${MESSENGER__API__ROOT_URL:-http://localhost:3000/messenger}${MESSENGER__API__ROOT_PATH}/openapi.json",
            "name": "Messenger",
          },
        ]
      BASE_URL: ${SWAGGER__API__ROOT_PATH:-/swagger}
    healthcheck:
      test: curl --fail http://localhost:8080${SWAGGER__API__ROOT_PATH:-/swagger}
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.swagger.rule=PathPrefix(`${SWAGGER__API__ROOT_PATH:-/swagger}`)"
        - "traefik.http.routers.swagger.entrypoints=web" 
        - "traefik.http.services.swagger.loadbalancer.server.port=8080"
      update_config:
        order: start-first
      replicas: 1

  proxy:
    image: traefik:v2.10
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - target: 80
        published: ${PORT:-3000}
        mode: host
    command:
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    deploy:
      update_config:
        order: start-first
      replicas: 1

secrets:
  oauth2_habr_client_id:
    external: true
    name: ${OAUTH2_HABR_CLIENT_ID_NAME:-oauth2_habr_client_id}
  oauth2_habr_client_secret:
    external: true
    name: ${OAUTH2_HABR_CLIENT_SECRET_NAME:-oauth2_habr_client_secret}
  habr_api_key:
    external: true
    name: ${HABR_API_KEY_NAME:-habr_api_key}
  habr_career_api_key:
    external: true
    name: ${HABR_CAREER_API_KEY_NAME:-habr_career_api_key}
  postgresql_password:
    external: true
    name: ${POSTGRESQL_PASSWORD_NAME:-postgresql_password}
  jwt_access_token_private_key:
    external: true
    name: ${JWT_ACCESS_TOKEN_PRIVATE_KEY_NAME:-jwt_access_token_private_key}
  jwt_access_token_public_key:
    external: true
    name: ${JWT_ACCESS_TOKEN_PUBLIC_KEY_NAME:-jwt_access_token_public_key}
  jwt_refresh_token_private_key:
    external: true
    name: ${JWT_REFRESH_TOKEN_PRIVATE_KEY_NAME:-jwt_refresh_token_private_key}
  jwt_refresh_token_public_key:
    external: true
    name: ${JWT_REFRESH_TOKEN_PUBLIC_KEY_NAME:-jwt_refresh_token_public_key}
