"""init

Revision ID: 75c501b95855
Revises: 
Create Date: 2023-11-07 12:11:11.792026

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "75c501b95855"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("skills",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("habr_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("habr_id"),
    )
    op.create_table("specialization_groups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("habr_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("name_en", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("habr_id"),
    )
    op.create_table("specializations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("habr_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("name_en", sa.String(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["specialization_groups.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("habr_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("specializations")
    op.drop_table("specialization_groups")
    op.drop_table("skills")
    # ### end Alembic commands ###
