


"""empty message

Revision ID: 08df701e31a0
Revises: 24c3d39b39e4
Create Date: 2023-10-18 10:21:35.737364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08df701e31a0'
down_revision: Union[str, None] = '24c3d39b39e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_participants', sa.Column('joined_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_participants', 'joined_at')
    # ### end Alembic commands ###
