


"""add project positions skills table

Revision ID: 9b2837e97a8d
Revises: 4137570d05c6
Create Date: 2023-10-26 20:17:49.837718

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9b2837e97a8d'
down_revision: Union[str, None] = '4137570d05c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_positions_skills',
    sa.Column('position_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['project_positions.id'], ),
    sa.PrimaryKeyConstraint('position_id', 'skill_id')
    )
    op.add_column('project_positions', sa.Column('specialization_id', sa.Uuid(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_positions', 'specialization_id')
    op.drop_table('project_positions_skills')
    # ### end Alembic commands ###
