name: Autotests Stage
on:
  schedule:
    - cron: "43 * * * *"
  workflow_dispatch: {}
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Build
        run: docker build -t sapphire:test-${{ github.sha }} --target full .
  test:
    needs: [build]
    runs-on: self-hosted
    steps:
      - name: Autotests
        run: >
          docker run --rm
          -e "MESSENGER_BASE_URL=${MESSENGER_ROOT_URL_STAGE}${MESSENGER_ROOT_PATH_STAGE}"
          -e "NOTIFICATIONS_BASE_URL=${NOTIFICATIONS_ROOT_URL_STAGE}${NOTIFICATIONS_ROOT_PATH_STAGE}"
          -e "PROJECTS_BASE_URL=${PROJECTS_ROOT_URL_STAGE}${PROJECTS_ROOT_PATH_STAGE}"
          -e "STORAGE_BASE_URL=${STORAGE_ROOT_URL_STAGE}${STORAGE_ROOT_PATH_STAGE}"
          -e "USERS_BASE_URL=${USERS_ROOT_URL_STAGE}${USERS_ROOT_PATH_STAGE}"
          -e "JWT_ACCESS_TOKEN_PRIVATE_KEY=${JWT_ACCESS_TOKEN_PRIVATE_KEY_STAGE}"
          -e "JWT_ACCESS_TOKEN_PUBLIC_KEY=${JWT_ACCESS_TOKEN_PUBLIC_KEY_STAGE}"
          -e "JWT_REFRESH_TOKEN_PRIVATE_KEY=${JWT_REFRESH_TOKEN_PRIVATE_KEY_STAGE}"
          -e "JWT_REFRESH_TOKEN_PUBLIC_KEY=${JWT_REFRESH_TOKEN_PUBLIC_KEY_STAGE}"
          sapphire:test-${{ github.sha }} pytest autotests
