name: Autotests Stage
on:
  schedule:
    - cron: "43 * * * *"
  workflow_dispatch: {}
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Build
        run: docker build -t sapphire:test-${{ github.sha }} --target full .
  test:
    needs: [build]
    runs-on: self-hosted
    steps:
      - name: Autotests
        run: >
          docker run --rm
          -e "MESSENGER_BASE_URL=${MESSENGER_ROOT_URL_STAGE}${MESSENGER_ROOT_PATH_STAGE}"
          -e "NOTIFICATIONS_BASE_URL=${NOTIFICATIONS_ROOT_URL_STAGE}${NOTIFICATIONS_ROOT_PATH_STAGE}"
          -e "PROJECTS_BASE_URL=${PROJECTS_ROOT_URL_STAGE}${PROJECTS_ROOT_PATH_STAGE}"
          -e "STORAGE_BASE_URL=${STORAGE_ROOT_URL_STAGE}${STORAGE_ROOT_PATH_STAGE}"
          -e "USERS_BASE_URL=${USERS_ROOT_URL_STAGE}${USERS_ROOT_PATH_STAGE}"
          -e "MESSENGER_WEBSOCKET_URL=${MESSENGER_WEBSOCKET_URL_STAGE}"
          -e "NOTIFICATIONS_WEBSOCKET_URL=${NOTIFICATIONS_WEBSOCKET_URL_STAGE}"
          -e "HABR_OAUTH2_CALLBACK_URL=${USERS_HABR_OAUTH2_CALLBACK_URL_STAGE}"
          -e "OLEG_ID=${OLEG_ID}"
          -e "OLEG_EMAIL=${OLEG_EMAIL}"
          -e "OLEG_EMAIL_PASSWORD=${OLEG_EMAIL_PASSWORD}"
          -e "MATVEY_ID=${MATVEY_ID}"
          -e "MATVEY_EMAIL=${MATVEY_EMAIL}"
          -e "MATVEY_EMAIL_PASSWORD=${MATVEY_EMAIL_PASSWORD}"
          -e "PROJECT_ID=${PROJECT_ID}"
          -e "POSITION_ID=${POSITION_ID}"
          -e "PARTICIPANT_ID=${PARTICIPANT_ID}"
          -e "CHAT_ID=${CHAT_ID}"
          -v /sapphire/stage/secrets:/run/secrets
          sapphire:test-${{ github.sha }} pytest autotests
      - name: Notification
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            @WainsCat @vanvanich9 @brulitsan @OlegYurchik
            Autotests Failed
            Last commit: https://github.com/${{ github.repository }}/commit/${{github.sha}}
