name: Autotests Stage
on:
  schedule:
    - cron: "43 * * * *"
  workflow_dispatch: {}
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Build
        run: docker build -t sapphire:test-${{ github.sha }} --target full .
  test:
    needs: [build]
    runs-on: self-hosted
    steps:
      - name: Autotests
        run: >
          docker run --rm
          -e "MESSENGER_BASE_URL=${STAGE__COLLABRY__MESSENGER__API__ROOT_URL}${STAGE__COLLABRY__MESSENGER__API__ROOT_PATH}"
          -e "NOTIFICATIONS_BASE_URL=${STAGE__COLLABRY__NOTIFICATIONS__API__ROOT_URL}${STAGE__COLLABRY__NOTIFICATIONS__API__ROOT_PATH}"
          -e "PROJECTS_BASE_URL=${STAGE__COLLABRY__PROJECTS__API__ROOT_URL}${STAGE__COLLABRY__PROJECTS__API__ROOT_PATH}"
          -e "STORAGE_BASE_URL=${STAGE__COLALBRY__STORAGE__API__ROOT_URL}${STAGE__COLLABRY__STORAGE__API__ROOT_PATH}"
          -e "USERS_BASE_URL=${STAGE__COLALBRY__USERS__API__ROOT_URL}${STAGE__COLLABRY__USERS__API__ROOT_PATH}"
          -e "OAUTH2_HABR_CALLBACK_URL=${STAGE__COLLABRY__USERS__API__OAUTH2_HABR_CALLBACK_URL}"
          -e "OLEG_EMAIL=${OLEG_EMAIL}"
          -e "OLEG_EMAIL_PASSWORD=${OLEG_EMAIL_PASSWORD}"
          -e "MATVEY_EMAIL=${MATVEY_EMAIL}"
          -e "MATVEY_EMAIL_PASSWORD=${MATVEY_EMAIL_PASSWORD}"
          -v /sapphire/stage/secrets:/run/secrets
          sapphire:test-${{ github.sha }} pytest autotests
      - name: Notification
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            @WainsCat @vanvanich9 @brulitsan @OlegYurchik
            Autotests Failed
            Last commit: https://github.com/${{ github.repository }}/commit/${{github.sha}}
