name: Deploy Stage
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: docker build -t sapphire:${{ github.sha }} --target slim .
  deploy:
    needs: [build]
    runs-on: self-hosted
    steps:
      - name: Set environment variables
        run: |
          echo "ENV=production" >> $GITHUB_ENV
          echo "SAPPHIRE_IMAGE=sapphire:${GITHUB_SHA}" >> $GITHUB_ENV
          echo "PORT=${STAGE__PORT}" >> $GITHUB_ENV
          echo "OAUTH2_HABR_CLIENT_ID_NAME=${STAGE__OAUTH2_HABR_CLIENT_ID_NAME}" >> $GITHUB_ENV
          echo "OAUTH2_HABR_CLIENT_SECRET_NAME=${STAGE__OAUTH2_HABR_CLIENT_SECRET_NAME}" >> $GITHUB_ENV
          echo "HABR_API_KEY_NAME=${STAGE__HABR_API_KEY_NAME}" >> $GITHUB_ENV
          echo "HABR_CAREER_API_KEY_NAME=${STAGE__HABR_CAREER_API_KEY_NAME}" >> $GITHUB_ENV
          echo "JWT_ACCESS_TOKEN_PRIVATE_KEY_NAME=${STAGE__JWT_ACCESS_TOKEN_PRIVATE_KEY_NAME}" >> $GITHUB_ENV
          echo "JWT_ACCESS_TOKEN_PUBLIC_KEY_NAME=${STAGE__JWT_ACCESS_TOKEN_PUBLIC_KEY_NAME}" >> $GITHUB_ENV
          echo "JWT_REFRESH_TOKEN_PRIVATE_KEY_NAME=${STAGE__JWT_REFRESH_TOKEN_PRIVATE_KEY_NAME}" >> $GITHUB_ENV
          echo "JWT_REFRESH_TOKEN_PUBLIC_KEY_NAME=${STAGE__JWT_REFRESH_TOKEN_PUBLIC_KEY_NAME}" >> $GITHUB_ENV
          echo "POSTGRESQL_PASSWORD_NAME=${STAGE__POSTGRESQL_PASSWORD_NAME}" >> $GITHUB_ENV
          echo "SWAGGER_ROOT_PATH=${STAGE__SWAGGER_ROOT_PATH}" >> $GITHUB_ENV
          echo "KAFKA_UI_ROOT_PATH=${STAGE__KAFKA_UI_ROOT_PATH}" >> $GITHUB_ENV
          echo "KAFKA_UI_PASSWORD=${STAGE__KAFKA_UI_PASSWORD}" >> $GITHUB_ENV
          echo "BROKER_DIR=${STAGE__BROKER_DIR}" >> $GITHUB_ENV
          echo "DATABASE_DIR=${STAGE__DATABASE_DIR}" >> $GITHUB_ENV
          echo "REDIS_DIR=${STAGE__REDIS_DIR}" >> $GITHUB_ENV
          echo "PROJECTS_MEDIA_DIR_PATH=${STAGE__PROJECTS_MEDIA_DIR_PATH}" >> $GITHUB_ENV
          echo "USERS_MEDIA_DIR_PATH=${STAGE__USERS_MEDIA_DIR_PATH}" >> $GITHUB_ENV
          echo "MESSENGER__API__ALLOWED_ORIGINS=${STAGE__MESSENGER__API__ALLOWED_ORIGINS}" >> $GITHUB_ENV
          echo "MESSENGER__API__ROOT_PATH=${STAGE__MESSENGER__API__ROOT_PATH}" >> $GITHUB_ENV
          echo "MESSENGER__API__ROOT_URL=${STAGE__MESSENGER__API__ROOT_URL}" >> $GITHUB_ENV
          echo "MESSENGER__DATABASE__DSN=${STAGE__MESSENGER__DATABASE__DSN}" >> $GITHUB_ENV
          echo "NOTIFICATIONS__API__ALLOWED_ORIGINS=${STAGE__NOTIFICATIONS__API__ALLOWED_ORIGINS}" >> $GITHUB_ENV
          echo "NOTIFICATIONS__API__ROOT_PATH=${STAGE__NOTIFICATIONS__API__ROOT_PATH}" >> $GITHUB_ENV
          echo "NOTIFICATIONS__API__ROOT_URL=${STAGE__NOTIFICATIONS__API__ROOT_URL}" >> $GITHUB_ENV
          echo "NOTIFICATIONS__DATABASE__DSN=${STAGE__NOTIFICATIONS__DATABASE__DSN}" >> $GITHUB_ENV
          echo "PROJECTS__API__ALLOWED_ORIGINS=${STAGE__PROJECTS__API__ALLOWED_ORIGINS}" >> $GITHUB_ENV
          echo "PROJECTS__API__ROOT_PATH=${STAGE__PROJECTS__API__ROOT_PATH}" >> $GITHUB_ENV
          echo "PROJECTS__API__ROOT_URL=${STAGE__PROJECTS__API__ROOT_URL}" >> $GITHUB_ENV
          echo "PROJECTS__DATABASE__DSN=${STAGE__PROJECTS__DATABASE__DSN}" >> $GITHUB_ENV
          echo "STORAGE__API__ALLOWED_ORIGINS=${STAGE__STORAGE__API__ALLOWED_ORIGINS}" >> $GITHUB_ENV
          echo "STORAGE__API__ROOT_PATH=${STAGE__STORAGE__API__ROOT_PATH}" >> $GITHUB_ENV
          echo "STORAGE__API__ROOT_URL=${STAGE__STORAGE__API__ROOT_URL}" >> $GITHUB_ENV
          echo "STORAGE__DATABASE__DSN=${STAGE__STORAGE__DATABASE__DSN}" >> $GITHUB_ENV
          echo "USERS__API__ALLOWED_ORIGINS=${STAGE__USERS__API__ALLOWED_ORIGINS}" >> $GITHUB_ENV
          echo "USERS__API__OAUTH2_HABR_CALLBACK_URL=${STAGE__USERS__API__OAUTH2_HABR_CALLBACK_URL}" >> $GITHUB_ENV
          echo "USERS__API__ROOT_PATH=${STAGE__USERS__API__ROOT_PATH}" >> $GITHUB_ENV
          echo "USERS__API__ROOT_URL=${STAGE__USERS__API__ROOT_URL}" >> $GITHUB_ENV
          echo "USERS__DATABASE__DSN=${STAGE__USERS__DATABASE__DSN}" >> $GITHUB_ENV
      - name: Deploy
        run: docker stack deploy -c docker-compose.yaml sapphire-stage
