name: Deploy Production
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch: {}
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: docker build -t sapphire:${{ github.ref_name }} --target slim .
  deploy:
    needs: [build]
    runs-on: self-hosted
    steps:
      - name: Set environment variables
        run: |
          echo "ENV=production" >> $GITHUB_ENV
          echo "SAPPHIRE_IMAGE=sapphire:${GITHUB_SHA}" >> $GITHUB_ENV
          echo "PORT=${PRODUCTION__PORT}" >> $GITHUB_ENV
          echo "OAUTH2_HABR_CLIENT_ID_NAME=${PRODUCTION__OAUTH2_HABR_CLIENT_ID_NAME}" >> $GITHUB_ENV
          echo "OAUTH2_HABR_CLIENT_SECRET_NAME=${PRODUCTION__OAUTH2_HABR_CLIENT_SECRET_NAME}" >> $GITHUB_ENV
          echo "HABR_API_KEY_NAME=${PRODUCTION__HABR_API_KEY_NAME}" >> $GITHUB_ENV
          echo "HABR_CAREER_API_KEY_NAME=${PRODUCTION__HABR_CAREER_API_KEY_NAME}" >> $GITHUB_ENV
          echo "JWT_ACCESS_TOKEN_PRIVATE_KEY_NAME=${PRODUCTION__JWT_ACCESS_TOKEN_PRIVATE_KEY_NAME}" >> $GITHUB_ENV
          echo "JWT_ACCESS_TOKEN_PUBLIC_KEY_NAME=${PRODUCTION__JWT_ACCESS_TOKEN_PUBLIC_KEY_NAME}" >> $GITHUB_ENV
          echo "JWT_REFRESH_TOKEN_PRIVATE_KEY_NAME=${PRODUCTION__JWT_REFRESH_TOKEN_PRIVATE_KEY_NAME}" >> $GITHUB_ENV
          echo "JWT_REFRESH_TOKEN_PUBLIC_KEY_NAME=${PRODUCTION__JWT_REFRESH_TOKEN_PUBLIC_KEY_NAME}" >> $GITHUB_ENV
          echo "DATABASE_PASSWORD=${PRODUCTION__DATABASE_PASSWORD}" >> $GITHUB_ENV
          echo "SWAGGER_ROOT_PATH=${PRODUCTION__SWAGGER_ROOT_PATH}" >> $GITHUB_ENV
          echo "KAFKA_UI_ROOT_PATH=${PRODUCTION__KAFKA_UI_ROOT_PATH}" >> $GITHUB_ENV
          echo "KAFKA_UI_PASSWORD=${PRODUCTION__KAFKA_UI_PASSWORD}" >> $GITHUB_ENV
          echo "BROKER_DIR=${PRODUCTION__BROKER_DIR}" >> $GITHUB_ENV
          echo "DATABASE_DIR=${PRODUCTION__DATABASE_DIR}" >> $GITHUB_ENV
          echo "REDIS_DIR=${PRODUCTION__REDIS_DIR}" >> $GITHUB_ENV
          echo "PROJECTS_MEDIA_DIR_PATH=${PRODUCTION__PROJECTS_MEDIA_DIR_PATH}" >> $GITHUB_ENV
          echo "USERS_MEDIA_DIR_PATH=${PRODUCTION__USERS_MEDIA_DIR_PATH}" >> $GITHUB_ENV
          echo "DATABASE__DSN=${PRODUCTION__DATABASE__DSN}" >> $GITHUB_ENV
          echo "MESSENGER__API__ALLOWED_ORIGINS=${PRODUCTION__MESSENGER__API__ALLOWED_ORIGINS}" >> $GITHUB_ENV
          echo "MESSENGER__API__ROOT_PATH=${PRODUCTION__MESSENGER__API__ROOT_PATH}" >> $GITHUB_ENV
          echo "MESSENGER__API__ROOT_URL=${PRODUCTION__MESSENGER__API__ROOT_URL}" >> $GITHUB_ENV
          echo "MESSENGER__DATABASE__DSN=${PRODUCTION__MESSENGER__DATABASE__DSN}" >> $GITHUB_ENV
          echo "NOTIFICATIONS__API__ALLOWED_ORIGINS=${PRODUCTION__NOTIFICATIONS__API__ALLOWED_ORIGINS}" >> $GITHUB_ENV
          echo "NOTIFICATIONS__API__ROOT_PATH=${PRODUCTION__NOTIFICATIONS__API__ROOT_PATH}" >> $GITHUB_ENV
          echo "NOTIFICATIONS__API__ROOT_URL=${PRODUCTION__NOTIFICATIONS__API__ROOT_URL}" >> $GITHUB_ENV
          echo "NOTIFICATIONS__DATABASE__DSN=${PRODUCTION__NOTIFICATIONS__DATABASE__DSN}" >> $GITHUB_ENV
          echo "PROJECTS__API__ALLOWED_ORIGINS=${PRODUCTION__PROJECTS__API__ALLOWED_ORIGINS}" >> $GITHUB_ENV
          echo "PROJECTS__API__ROOT_PATH=${PRODUCTION__PROJECTS__API__ROOT_PATH}" >> $GITHUB_ENV
          echo "PROJECTS__API__ROOT_URL=${PRODUCTION__PROJECTS__API__ROOT_URL}" >> $GITHUB_ENV
          echo "PROJECTS__DATABASE__DSN=${PRODUCTION__PROJECTS__DATABASE__DSN}" >> $GITHUB_ENV
          echo "STORAGE__API__ALLOWED_ORIGINS=${PRODUCTION__STORAGE__API__ALLOWED_ORIGINS}" >> $GITHUB_ENV
          echo "STORAGE__API__ROOT_PATH=${PRODUCTION__STORAGE__API__ROOT_PATH}" >> $GITHUB_ENV
          echo "STORAGE__API__ROOT_URL=${PRODUCTION__STORAGE__API__ROOT_URL}" >> $GITHUB_ENV
          echo "STORAGE__DATABASE__DSN=${PRODUCTION__STORAGE__DATABASE__DSN}" >> $GITHUB_ENV
          echo "USERS__API__ALLOWED_ORIGINS=${PRODUCTION__USERS__API__ALLOWED_ORIGINS}" >> $GITHUB_ENV
          echo "USERS__API__OAUTH2_HABR_CALLBACK_URL=${PRODUCTION__USERS__API__OAUTH2_HABR_CALLBACK_URL}" >> $GITHUB_ENV
          echo "USERS__API__ROOT_PATH=${PRODUCTION__USERS__API__ROOT_PATH}" >> $GITHUB_ENV
          echo "USERS__API__ROOT_URL=${PRODUCTION__USERS__API__ROOT_URL}" >> $GITHUB_ENV
          echo "USERS__DATABASE__DSN=${PRODUCTION__USERS__DATABASE__DSN}" >> $GITHUB_ENV
      - name: Deploy
        run: docker stack deploy -c docker-compose.yaml sapphire-production
