name: Deploy Production
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: docker build -t sapphire:${{ github.ref_name }} --target slim .
  deploy:
    needs: [build]
    runs-on: self-hosted
    steps:
      - name: Set environment variables
        run: |
          echo "HABR_OAUTH2_CLIENT_ID_NAME=habr_oauth2_client_id_production" >> $GITHUB_ENV
          echo "HABR_OAUTH2_CLIENT_SECRET_NAME=habr_oauth2_client_secret_production" >> $GITHUB_ENV
          echo "JWT_ACCESS_TOKEN_PRIVATE_KEY_NAME=jwt_access_token_private_key_production" >> $GITHUB_ENV
          echo "JWT_ACCESS_TOKEN_PUBLIC_KEY_NAME=jwt_access_token_public_key_production" >> $GITHUB_ENV
          echo "JWT_REFRESH_TOKEN_PRIVATE_KEY_NAME=jwt_refresh_token_private_key_production" >> $GITHUB_ENV
          echo "JWT_REFRESH_TOKEN_PUBLIC_KEY_NAME=jwt_refresh_token_public_key_production" >> $GITHUB_ENV
          echo "POSTGRESQL_PASSWORD_NAME=postgresql_password_production" >> $GITHUB_ENV
          echo "DATABASE_DIR=/sapphire/production/database_data" >> $GITHUB_ENV
          echo "REDIS_DIR=/sapphire/production/redis_data" >> $GITHUB_ENV
          echo "BROKER_DIR=/sapphire/production/broker_dir" >> $GITHUB_ENV
          echo "SAPPHIRE_IMAGE=sapphire:${GITHUB_SHA}" >> $GITHUB_ENV
          echo "USERS_BASE_URL=${USERS_BASE_URL_PRODUCTION}" >> $GITHUB_ENV
          echo "USERS_PORT=2000" >> $GITHUB_ENV
          echo "USERS_DB_DSN=${USERS_DB_DSN_PRODUCTION}" >> $GITHUB_ENV
          echo "USERS_ROOT_PATH=${USERS_ROOT_PATH_PRODUCTION}" >> $GITHUB_ENV
          echo "USERS_ALLOWED_ORIGINS=${USERS_ALLOWED_ORIGINS_PRODUCTION}" >> $GITHUB_ENV
          echo "PROJECTS_BASE_URL=${PROJECTS_BASE_URL_PRODUCTION}" >> $GITHUB_ENV
          echo "PROJECTS_PORT=2020" >> $GITHUB_ENV
          echo "PROJECTS_DB_DSN=${PROJECTS_DB_DSN_PRODUCTION}" >> $GITHUB_ENV
          echo "PROJECTS_ROOT_PATH=${PROJECTS_ROOT_PATH_PRODUCTION}" >> $GITHUB_ENV
          echo "PROJECTS_ALLOWED_ORIGINS=${PROJECTS_ALLOWED_ORIGINS_PRODUCTION}" >> $GITHUB_ENV
      - name: Deploy
        run: docker stack deploy -c docker-compose.yaml sapphire-stage
