name: Deploy Production
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]"
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: docker build -t sapphire:${{ github.ref_name }} --target app .
  deploy:
    needs: [build]
    runs-on: self-hosted
    steps:
      - name: Deploy
        env:
          DATABASE_DIR: "/sapphire/production/database_data"
          REDIS_DIR: "/sapphire/production/redis_data"
          BROKER_DIR: "/sapphire/production/broker_dir"
          SAPPHIRE_IMAGE: sapphire:{{ github.ref_name }}
          USERS_PORT: "3000"
          USERS_DB_DSN: ${USERS_DB_DSN_PRODUCTION}
          PROJECTS_PORT: "3020"
          PROJECTS_DB_DSN: ${PROJECTS_DB_DSN_PRODUCTION}
        run: docker stack deploy -c docker-compose.yaml sapphire-stage
