name: Deploy Production
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch: {}
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: docker build -t collabry:${{ github.ref_name }} --target slim .
  deploy:
    needs: [build]
    runs-on: self-hosted
    steps:
      - name: Set environment variables
        run: |
          echo "ENV=production" >> $GITHUB_ENV
          echo "COLLABRY__IMAGE=collabry:${GITHUB_SHA}" >> $GITHUB_ENV
          for e in $(env | grep 'PRODUCTION__'); do echo "${e#'PRODUCTION__'}" >> $GITHUB_ENV; done
          # echo "TRAEFIK__PORT=${PRODUCTION__TRAEFIK__PORT}" >> $GITHUB_ENV
          # echo "SECRETS__OAUTH2_HABR_CLIENT_ID_NAME=${PRODUCTION__SECRETS__OAUTH2_HABR_CLIENT_ID_NAME}" >> $GITHUB_ENV
          # echo "SECRETS__OAUTH2_HABR_CLIENT_SECRET_NAME=${PRODUCTION__SECRETS__OAUTH2_HABR_CLIENT_SECRET_NAME}" >> $GITHUB_ENV
          # echo "SECRETS__HABR_API_KEY_NAME=${PRODUCTION__SECRETS__HABR_API_KEY_NAME}" >> $GITHUB_ENV
          # echo "SECRETS__HABR_CAREER_API_KEY_NAME=${PRODUCTION__SECRETS__HABR_CAREER_API_KEY_NAME}" >> $GITHUB_ENV
          # echo "SECRETS__JWT_ACCESS_TOKEN_PRIVATE_KEY_NAME=${PRODUCTION__SECRETS__JWT_ACCESS_TOKEN_PRIVATE_KEY_NAME}" >> $GITHUB_ENV
          # echo "SECRETS__JWT_ACCESS_TOKEN_PUBLIC_KEY_NAME=${PRODUCTION__SECRETS__JWT_ACCESS_TOKEN_PUBLIC_KEY_NAME}" >> $GITHUB_ENV
          # echo "SECRETS__JWT_REFRESH_TOKEN_PRIVATE_KEY_NAME=${PRODUCTION__SECRETS__JWT_REFRESH_TOKEN_PRIVATE_KEY_NAME}" >> $GITHUB_ENV
          # echo "SECRETS__JWT_REFRESH_TOKEN_PUBLIC_KEY_NAME=${PRODUCTION__SECRETS__JWT_REFRESH_TOKEN_PUBLIC_KEY_NAME}" >> $GITHUB_ENV
          # echo "POSTGRES__PASSWORD=${PRODUCTION__POSTGRES__PASSWORD}" >> $GITHUB_ENV
          # echo "SWAGGER__ROOT_PATH=${PRODUCTION__SWAGGER__ROOT_PATH}" >> $GITHUB_ENV
          # echo "KAFKA_UI__ROOT_PATH=${PRODUCTION__KAFKA_UI__ROOT_PATH}" >> $GITHUB_ENV
          # echo "KAFKA_UI__PASSWORD=${PRODUCTION__KAFKA_UI__PASSWORD}" >> $GITHUB_ENV
          # echo "GRAFANA__ROOT_URL=${PRODUCTION__GRAFANA__ROOT_URL}" >> $GITHUB_ENV
          # echo "GRAFANA__ROOT_PATH=${PRODUCTION__GRAFANA__ROOT_PATH}" >> $GITHUB_ENV
          # echo "COLLABRY__DATABASE__DSN=${PRODUCTION__COLLABRY__DATABASE__DSN}" >> $GITHUB_ENV
          # echo "COLLABRY__EMAIL__SENDER__USERNAME=${PRODUCTION__COLLABRY__EMAIL__SENDER__USERNAME}" >> $GITHUB_ENV
          # echo "COLLABRY__EMAIL__SENDER__PASSWORD=${PRODUCTION__COLLABRY__EMAIL__SENDER__PASSWORD}" >> $GITHUB_ENV
          # echo "COLLABRY__EMAIL__SENDER__HOST=${PRODUCTION__COLLABRY__EMAIL__SENDER__HOST}" >> $GITHUB_ENV
          # echo "COLLABRY__EMAIL__SENDER__PORT=${PRODUCTION__COLLABRY__EMAIL__SENDER__PORT}" >> $GITHUB_ENV
          # echo "COLLABRY__EMAIL__SENDER__START_TLS=${PRODUCTION__COLLABRY__EMAIL__SENDER__START_TLS}" >> $GITHUB_ENV
          # echo "COLLABRY__EMAIL__SENDER__TLS=${PRODUCTION__COLLABRY__EMAIL__SENDER__TLS}" >> $GITHUB_ENV
          # echo "COLLABRY__MESSENGER__API__ALLOWED_ORIGINS=${PRODUCTION__COLLABRY__MESSENGER__API__ALLOWED_ORIGINS}" >> $GITHUB_ENV
          # echo "COLLABRY__MESSENGER__API__ROOT_PATH=${PRODUCTION__COLLABRY__MESSENGER__API__ROOT_PATH}" >> $GITHUB_ENV
          # echo "COLLABRY__MESSENGER__API__ROOT_URL=${PRODUCTION__COLLABRY__MESSENGER__API__ROOT_URL}" >> $GITHUB_ENV
          # echo "COLLABRY__MESSENGER__DATABASE__DSN=${PRODUCTION__COLLABRY__MESSENGER__DATABASE__DSN}" >> $GITHUB_ENV
          # echo "COLLABRY__NOTIFICATIONS__API__ALLOWED_ORIGINS=${PRODUCTION__COLLABRY__NOTIFICATIONS__API__ALLOWED_ORIGINS}" >> $GITHUB_ENV
          # echo "COLLABRY__NOTIFICATIONS__API__ROOT_PATH=${PRODUCTION__COLLABRY__NOTIFICATIONS__API__ROOT_PATH}" >> $GITHUB_ENV
          # echo "COLLABRY__NOTIFICATIONS__API__ROOT_URL=${PRODUCTION__COLLABRY__NOTIFICATIONS__API__ROOT_URL}" >> $GITHUB_ENV
          # echo "COLLABRY__NOTIFICATIONS__DATABASE__DSN=${PRODUCTION__COLLABRY__NOTIFICATIONS__DATABASE__DSN}" >> $GITHUB_ENV
          # echo "COLLABRY__PROJECTS__API__ALLOWED_ORIGINS=${PRODUCTION__COLLABRY__PROJECTS__API__ALLOWED_ORIGINS}" >> $GITHUB_ENV
          # echo "COLLABRY__PROJECTS__API__ROOT_PATH=${PRODUCTION__COLLABRY__PROJECTS__API__ROOT_PATH}" >> $GITHUB_ENV
          # echo "COLLABRY__PROJECTS__API__ROOT_URL=${PRODUCTION__COLLABRY__PROJECTS__API__ROOT_URL}" >> $GITHUB_ENV
          # echo "COLLABRY__PROJECTS__DATABASE__DSN=${PRODUCTION__COLLABRY__PROJECTS__DATABASE__DSN}" >> $GITHUB_ENV
          # echo "COLLABRY__STORAGE__API__ALLOWED_ORIGINS=${PRODUCTION__COLLABRY__STORAGE__API__ALLOWED_ORIGINS}" >> $GITHUB_ENV
          # echo "COLLABRY__STORAGE__API__ROOT_PATH=${PRODUCTION__COLLABRY__STORAGE__API__ROOT_PATH}" >> $GITHUB_ENV
          # echo "COLLABRY__STORAGE__API__ROOT_URL=${PRODUCTION__COLLABRY__STORAGE__API__ROOT_URL}" >> $GITHUB_ENV
          # echo "COLLABRY__STORAGE__DATABASE__DSN=${PRODUCTION__COLLABRY__STORAGE__DATABASE__DSN}" >> $GITHUB_ENV
          # echo "COLLABRY__USERS__API__ALLOWED_ORIGINS=${PRODUCTION__COLLABRY__USERS__API__ALLOWED_ORIGINS}" >> $GITHUB_ENV
          # echo "COLLABRY__USERS__API__OAUTH2_HABR_CALLBACK_URL=${PRODUCTION__COLLABRY__USERS__API__OAUTH2_HABR_CALLBACK_URL}" >> $GITHUB_ENV
          # echo "COLLABRY__USERS__API__ROOT_PATH=${PRODUCTION__COLLABRY__USERS__API__ROOT_PATH}" >> $GITHUB_ENV
          # echo "COLLABRY__USERS__API__ROOT_URL=${PRODUCTION__COLLABRY__USERS__API__ROOT_URL}" >> $GITHUB_ENV
          # echo "COLLABRY__USERS__DATABASE__DSN=${PRODUCTION__COLLABRY__USERS__DATABASE__DSN}" >> $GITHUB_ENV
      - name: Deploy
        run: docker stack deploy -c docker-compose.yaml collabry-production
