name: Integration
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: docker build -t sapphire:test-${{ github.sha }} --target full .
  lint:
    needs: [build]
    runs-on: self-hosted
    steps:
      - name: Lint
        run: >
          docker run sapphire:test-${{ github.sha }} pylint /app/sapphire /app/autotests /app/tests
  isort:
    needs: [build]
    runs-on: self-hosted
    steps:
      - name: Isort
        run: docker run sapphire:test-${{ github.sha }} isort --check .
  test:
    needs: [build]
    runs-on: self-hosted
    steps:
      - name: Test
        run: docker run sapphire:test-${{ github.sha }} pytest /app/tests
