name: Main
on: [push]
jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: docker build -t sapphire:lint-${{ github.sha }} --target lint .
      - name: Lint
        run: docker run sapphire:lint-${{ github.sha }}
  isort:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: docker build -t sapphire:isort-${{ github.sha }} --target isort .
      - name: Isort
        run: docker run sapphire:isort-${{ github.sha }}
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: docker build -t sapphire:test-${{ github.sha }} --target test .
      - name: Test
        run: docker run sapphire:test-${{ github.sha }}
